services:
  open-webui:
    ports:
      - 8088:8080
    # network_mode: host
    volumes:
      - /path/to/openwebui-data:/app/backend/data
      - /path/to/openwebui-data/docs:/data/docs
    environment:
      - OLLAMA_BASE_URL=http://192.168.7.2:8089
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
networks: {}
