services:
  wg-easy:
    container_name: wg-easy
    environment:
      - WG_HOST=192.168.7.2
      - PASSWORD=PASSWORD
    volumes:
      - /path/to/wgeasy-data:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 8085:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    image: ghcr.io/wg-easy/wg-easy
networks: {}
