services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    security_opt:
      - apparmor:unconfined
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8080:3000
    volumes:
      - /path/to/homepage-data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/to/host:/path/in/container
    restart: unless-stopped
networks: {}
