version: '3'
services:
  fusion:
    image: rook1e404/fusion:latest
    ports:
      - '8083:8080'
    environment:
      - PASSWORD=PutPassHere123
    restart: "unless-stopped"
    volumes:
      - /path/to/fusion-data/data:/data
