services:
  kopia:
    image: kopia/kopia:latest
    security_opt:
      - apparmor:unconfined
    hostname: Hostname
    container_name: Kopia
    restart: unless-stopped
    ports:
      - 8084:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=USER
      - --server-password=PASSWORD
    environment:
      # Set repository password
      KOPIA_PASSWORD: PASSWORD
      USER: USER
    volumes:
      # Mount local folders needed by kopia
      - /path/to/kopia-data/config:/app/config
      - /path/to/kopia-data/cache:/app/cache
      - /path/to/kopia-data/logs:/app/logs
      - /:/data:ro
      - /path/to/kopia/backups/dope:/repository
      - /path/to/kopia-data/tmp:/tmp:shared

