services:
  ghost-server:
    image: ghost
    cap_add:
      - CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    ports:
      - 8086:2368
    depends_on:
      - ghost-db
    environment:
      url: http://192.168.7.1:8086
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: PASSWORD
      database__connection__database: ghost
    volumes:
      - /path/to/ghost-data/content:/var/lib/ghost/content
  ghost-db:
    image: mysql:8
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    volumes:
      - /path/to/ghost-data/mysql:/var/lib/mysql

