services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/syncthing-data:/var/syncthing
    ports:
      - 8084:8384 # Web UI
    restart: unless-stopped
