services:
  photoview:
    image: viktorstrate/photoview:2
    labels:
      - com.centurylinklabs.watchtower.enable=true
    hostname: photoview
    container_name: photoview
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - 8088:80
    depends_on:
      mariadb:
        condition: service_healthy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOVIEW_DATABASE_DRIVER: mysql
      PHOTOVIEW_MYSQL_URL: photoview:photosecret@tcp(photoview-mariadb)/photoview
      PHOTOVIEW_LISTEN_IP: photoview
    volumes:
      - /etc/localtime:/etc/localtime:ro ## use local time from host
      - /etc/timezone:/etc/timezone:ro ## use timezone from host
      - /path/to/photoview-data/storage:/home/photoview/media-cache
      - /path/to/media/photos:/photos:ro
  mariadb:
    image: mariadb:lts
    hostname: photoview-mariadb
    container_name: photoview-mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    command: mariadbd --innodb-buffer-pool-size=512M
      --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci --max-connections=512
      --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DATABASE: photoview
      MARIADB_USER: photoview
      MARIADB_PASSWORD: photosecret
      MARIADB_ROOT_PASSWORD: superphotosecret
    volumes:
      - /etc/localtime:/etc/localtime:ro ## use local time from host
      - /etc/timezone:/etc/timezone:ro ## use timezone from host
      - /path/to/photoview-data/database/mariadb:/var/lib/mysql ## DO NOT REMOVE
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m
networks: {}

