services:
  livebook:
    ports:
      - 8085:8080
      - 8086:8081
    pull_policy: always
    user: 1000:1000
    volumes:
      - /path/to/livebook-data/data:/data
    image: ghcr.io/livebook-dev/livebook
    restart: unless-stopped
networks: {}
