services:
  db:
    image: mysql:5.7
    volumes:
      - /path/to/budibasedb-data/db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPASS
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: MySQLPASS
    networks:
      - mysql-phpmyadmin
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: MySQLPASS
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin: null
